CREATE TABLE T_CLIENTES(
    CLI_ID INT PRIMARY KEY AUTO_INCREMENT,
    CLI_UUID VARCHAR(40) UNIQUE NOT NULL,
    CLI_IDENTIFICACION VARCHAR(45) UNIQUE NOT NULL,
    CLI_NOMBRE VARCHAR(45) NOT NULL,
    CLI_DIRECCION VARCHAR(45) NOT NULL,
    CLI_TIPO_IDENTIFICACION_ID INT NOT NULL
);

CREATE TABLE T_USUARIOS(
    USUA_ID INT PRIMARY KEY AUTO_INCREMENT ,
    USUA_UUDI VARCHAR(40) UNIQUE NOT NULL ,
    USUA_NUM_IDENTIDAD INT UNIQUE NOT NULL,
    USUA_CORREO_ELECT VARCHAR(45) NOT NULL ,
    USUA_CONTRASEÑA VARCHAR(45) NOT NULL,
    USUA_ROL_ID INT NOT NULL
);

CREATE TABLE T_VENTAS(
    VENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENT_UUID VARCHAR(40) UNIQUE NOT NULL,
    VENT_PRO_CODIGO VARCHAR(45) UNIQUE NOT NULL,
    VENT_PRO_NOMBRE VARCHAR(45) UNIQUE NOT NULL,
    VENT_USUA_ID INT NOT NULL,
    VENT_CLI_ID INT NOT NULL
);

CREATE TABLE T_VENT_PROD(
    VENPRO_ID INT PRIMARY KEY AUTO_INCREMENT,
    VENPRO_UUID VARCHAR(40) UNIQUE NOT NULL,
    VENTPRO_CANTIDAD INT NOT NULL,
    VENPRO_VENT_ID INT NOT NULL,
    VENPRO_PROD_ID INT NOT NULL
);

CREATE TABLE T_PRODUCTOS(
    PROD_ID INT PRIMARY KEY AUTO_INCREMENT ,
    PROD_UUID VARCHAR(40) UNIQUE NOT NULL ,
    PROD_CODIGO VARCHAR(45) UNIQUE NOT NULL ,
    PROD_NOMBRE VARCHAR(45) NOT NULL ,
    PROD_CANTIDAD VARCHAR(45) NOT NULL ,
    PROD_PRECIO INT NOT NULL,
    PROD_TIPO_ID INT NOT NULL,
    PROD_UND_MEDIDA INT NOT NULL ,
    PROD_ETC_DET_ETC_ID INT NOT NULL
);

CREATE TABLE T_COTIZACIONES(
    COT_ID INT PRIMARY KEY AUTO_INCREMENT ,
    COT_UUID VARCHAR(40) UNIQUE NOT NULL ,
    COT_PRO_CODIGO INT UNIQUE NOT NULL ,
    COT_PRO_NOMBRE VARCHAR(45) NOT NULL ,
    COT_PRO_CANTIDAD INT NOT NULL ,
    COT_PRO_PRECIO INT NOT NULL,
    COT_TOTAL_PAGAR INT NOT NULL,
    COT_USUA_ID INT NOT NULL ,
    COT_CLI_ID INT NOT NULL
);

CREATE TABLE T_INSUMOS(
    INS_ID INT PRIMARY KEY AUTO_INCREMENT ,
    INS_UUID VARCHAR(40) UNIQUE NOT NULL ,
    INS_CODIGO VARCHAR(45) UNIQUE NOT NULL ,
    INS_NOMBRE VARCHAR(45) NOT NULL ,
    INS_CANTIDAD INT NOT NULL ,
    INS_PRECIO INT NOT NULL ,
    INS_USUA_ID INT NOT NULL ,
    INS_PROV_ID INT NOT NULL ,
    INS_TIPO_ID INT NOT NULL ,
    INS_UND_MEDIDA_ID INT NOT NULL
);

CREATE TABLE T_PRODU_ISUM(
    PROINSU_ID INT PRIMARY KEY AUTO_INCREMENT,
    PROINSU_UUID VARCHAR(40) UNIQUE NOT NULL,
    PROINSU_CANTIDAD INT NOT NULL,
    PROINSU_PROD_ID INT NOT NULL,
    PROINSU_INS_ID INT NOT NULL
);

CREATE TABLE T_CONTACTOS(
    CONT_ID INT PRIMARY KEY AUTO_INCREMENT,
    CONT_UUID VARCHAR(40) UNIQUE NOT NULL,
    CONT_TIPO_DATO VARCHAR(15) NOT NULL,
    CONT_CONTENIDO VARCHAR(45) NOT NULL,
    CONT_PROV_ID INT NOT NULL
);

CREATE TABLE T_PROVEEDORES(
    PROV_ID INT PRIMARY KEY AUTO_INCREMENT ,
    PROV_UUDI VARCHAR(40) UNIQUE NOT NULL ,
    PROV_IDENTIFICACION VARCHAR(45) UNIQUE NOT NULL,
    PROV_NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE T_ESTADOS_TIPOS_CATEGORIAS(
    ETC_ID INT PRIMARY KEY AUTO_INCREMENT,
    ETC_UUID VARCHAR(40) UNIQUE NOT NULL,
    ETC_NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE T_DETALLES_ETC(
    DET_ETC_ID INT PRIMARY KEY AUTO_INCREMENT,
    DET_ETC_UUID VARCHAR(40) UNIQUE NOT NULL,
    DET_ETC_NOMBRE VARCHAR(45) NOT NULL,
    DET_ETC_ETC_ID INT NOT NULL
);

ALTER TABLE T_CLIENTES ADD FOREIGN KEY(CLI_TIPO_IDENTIFICACION_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_USUARIOS ADD FOREIGN KEY(USUA_ROL_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_VENTAS ADD FOREIGN KEY(VENT_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_VENTAS ADD FOREIGN KEY(VENT_CLI_ID) REFERENCES T_CLIENTES(CLI_ID);
ALTER TABLE T_COTIZACIONES ADD FOREIGN KEY(COT_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_COTIZACIONES ADD FOREIGN KEY(COT_CLI_ID) REFERENCES T_CLIENTES(CLI_ID);
ALTER TABLE T_VENT_PROD ADD FOREIGN KEY(VENPRO_VENT_ID) REFERENCES T_VENTAS(VENT_ID);
ALTER TABLE T_VENT_PROD ADD FOREIGN KEY(VENPRO_PROD_ID) REFERENCES T_PRODUCTOS(PROD_ID);
ALTER TABLE T_PRODUCTOS ADD FOREIGN KEY(PROD_TIPO_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_PRODUCTOS ADD FOREIGN KEY(PROD_UND_MEDIDA) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_PRODUCTOS ADD FOREIGN KEY(PROD_ETC_DET_ETC_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_DETALLES_ETC ADD FOREIGN KEY(DET_ETC_ETC_ID) REFERENCES T_ESTADOS_TIPOS_CATEGORIAS(ETC_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY(INS_USUA_ID) REFERENCES T_USUARIOS(USUA_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY(INS_PROV_ID) REFERENCES T_PROVEEDORES(PROV_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY(INS_TIPO_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_INSUMOS ADD FOREIGN KEY(INS_UND_MEDIDA_ID) REFERENCES T_DETALLES_ETC(DET_ETC_ID);
ALTER TABLE T_PRODU_ISUM ADD FOREIGN KEY(PROINSU_PROD_ID) REFERENCES T_PRODUCTOS(PROD_ID);
ALTER TABLE T_PRODU_ISUM ADD FOREIGN KEY(PROINSU_INS_ID) REFERENCES T_INSUMOS(INS_ID);
ALTER TABLE T_CONTACTOS ADD FOREIGN KEY(CONT_PROV_ID) REFERENCES T_PROVEEDORES(PROV_ID);